package view;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.MouseInfo;
import java.awt.Point;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        togglemenu = false;
        pregistro.setVisible(false);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        left = new javax.swing.JPanel();
        inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pregistro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        rigth = new javax.swing.JPanel();
        usuario = new javax.swing.JTextField();
        contrasena = new javax.swing.JPasswordField();
        iconuser = new javax.swing.JLabel();
        enter = new javax.swing.JButton();
        textuser = new javax.swing.JLabel();
        textpassword = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        user = new javax.swing.JLabel();
        key = new javax.swing.JLabel();
        web1 = new javax.swing.JLabel();
        registrar1 = new javax.swing.JLabel();
        textpassword1 = new javax.swing.JLabel();
        menu = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        minimizar = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        left.setBackground(new java.awt.Color(255, 255, 255));
        left.setBorder(null);
        left.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inicio.setBackground(new java.awt.Color(255, 255, 255));
        inicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        inicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Acuerdos de Negocios Globales Diagrama de Venn (3) (1).png"))); // NOI18N
        inicio.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 360));

        left.add(inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        pregistro.setBackground(new java.awt.Color(255, 255, 255));
        pregistro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pregistro.setForeground(new java.awt.Color(26, 188, 156));
        pregistro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 188, 156));
        jLabel5.setText("Registrate");
        pregistro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jTextField2.setBackground(new java.awt.Color(204, 204, 204));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        pregistro.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 150, 30));

        jTextField3.setBackground(new java.awt.Color(204, 204, 204));
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        pregistro.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 150, 30));

        jTextField4.setBackground(new java.awt.Color(204, 204, 204));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        pregistro.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 150, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(26, 188, 156));
        jLabel6.setText("Correo Electronico");
        pregistro.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(26, 188, 156));
        jLabel8.setText("Apellido");
        pregistro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(26, 188, 156));
        jLabel9.setText("Numero de telefono");
        pregistro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(26, 188, 156));
        jLabel10.setText("Fecha de Nacimiento");
        pregistro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(26, 188, 156));
        jLabel11.setText("Nombre");
        pregistro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        pregistro.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 150, 30));

        jTextField11.setBackground(new java.awt.Color(204, 204, 204));
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        pregistro.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 150, 30));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(26, 188, 156));
        jLabel18.setText("Contraseña");
        pregistro.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jTextField14.setBackground(new java.awt.Color(204, 204, 204));
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(26, 188, 156)));
        pregistro.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 150, 30));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        pregistro.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 10, 230));
        pregistro.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 80, 20));
        pregistro.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 20));
        pregistro.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 80, 20));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-50.png"))); // NOI18N
        jButton1.setToolTipText("guardar");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-50 (1).png"))); // NOI18N
        pregistro.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        left.add(pregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 550));

        jPanel1.add(left, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 500, 550));

        rigth.setBackground(new java.awt.Color(255, 255, 255));
        rigth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        rigth.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuario.setBorder(null);
        usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioActionPerformed(evt);
            }
        });
        rigth.add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 160, 20));

        contrasena.setBorder(null);
        contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contrasenaActionPerformed(evt);
            }
        });
        rigth.add(contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 160, 20));

        iconuser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-64.png"))); // NOI18N
        rigth.add(iconuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 300, 100));

        enter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-log-in-64.png"))); // NOI18N
        enter.setToolTipText("iniciar sesion");
        enter.setBorder(null);
        enter.setContentAreaFilled(false);
        enter.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-log-in-64 (1).png"))); // NOI18N
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
        });
        rigth.add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, -1, 49));

        textuser.setBackground(new java.awt.Color(255, 0, 0));
        textuser.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        textuser.setForeground(new java.awt.Color(26, 188, 156));
        textuser.setText("Usuario");
        rigth.add(textuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        textpassword.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        textpassword.setForeground(new java.awt.Color(26, 188, 156));
        textpassword.setText("Olvido su usuario o contraseña?");
        textpassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textpasswordMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                textpasswordMousePressed(evt);
            }
        });
        rigth.add(textpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(26, 188, 156));
        jSeparator1.setForeground(new java.awt.Color(26, 188, 156));
        jSeparator1.setToolTipText("contrasena");
        jSeparator1.setBorder(null);
        rigth.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 210, 10));

        jSeparator2.setBackground(new java.awt.Color(26, 188, 156));
        jSeparator2.setForeground(new java.awt.Color(26, 188, 156));
        jSeparator2.setBorder(null);
        rigth.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 210, 10));

        user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-user-32.png"))); // NOI18N
        rigth.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        key.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-password-30.png"))); // NOI18N
        rigth.add(key, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        web1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Globe_32px.png"))); // NOI18N
        web1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                web1MouseClicked(evt);
            }
        });
        rigth.add(web1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, -1));

        registrar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-male-30.png"))); // NOI18N
        registrar1.setToolTipText("registrarse");
        registrar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registrar1MouseClicked(evt);
            }
        });
        rigth.add(registrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 30, -1));

        textpassword1.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 12)); // NOI18N
        textpassword1.setForeground(new java.awt.Color(26, 188, 156));
        textpassword1.setText("Contraseña");
        rigth.add(textpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jPanel1.add(rigth, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 300, 550));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menu-48.png"))); // NOI18N
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuMouseClicked(evt);
            }
        });
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel2.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel2.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        // TODO add your handling code here:
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    private void contrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contrasenaActionPerformed

    private void registrar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrar1MouseClicked
        // TODO add your handling code here:
        togglemenu = false;
        toggle = !toggle;
        if(toggle){
            pregistro.setVisible(true);
            inicio.setVisible(false);
        }else{
            pregistro.setVisible(false);
            inicio.setVisible(true);
        }
        minimizar.setVisible(true);
        cerrar.setVisible(true);
    }//GEN-LAST:event_registrar1MouseClicked

    private void menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseClicked
        // TODO add your handling code here:
        togglemenu = !togglemenu;
        if(togglemenu){
            web1.setVisible(false);
            registrar1.setVisible(false);
        }else{
            web1.setVisible(true);
            registrar1.setVisible(true);
        }
    }//GEN-LAST:event_menuMouseClicked

    private void textpasswordMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textpasswordMousePressed
        // TODO add your handling code here:
        textpassword.setForeground(Color.yellow);
    }//GEN-LAST:event_textpasswordMousePressed

    private void textpasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textpasswordMouseClicked
        // TODO add your handling code here:
        textpassword.setForeground(new Color(26,188,156));
    }//GEN-LAST:event_textpasswordMouseClicked

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked
        // TODO add your handling code here:
        String contrasenaU = "";
        for(char a:contrasena.getPassword())contrasenaU = contrasenaU + a;
        if(usuario.getText().equals("admin")&&contrasenaU.equals("root")){
            dispose();
            new Menu().setVisible(true);
        }
    }//GEN-LAST:event_enterMouseClicked

    private void web1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_web1MouseClicked
        try {
            // TODO add your handling code here:
            URI url = new URI("https://www.facebook.com/Nulleaks");
            Desktop.getDesktop().browse(url);
        } catch (URISyntaxException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_web1MouseClicked

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        Point locate = MouseInfo.getPointerInfo().getLocation();
        setLocation(locate.x,locate.y);
    }//GEN-LAST:event_formMouseDragged
    private boolean togglemenu;
    private boolean toggle;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel cerrar;
    private javax.swing.JPasswordField contrasena;
    private javax.swing.JButton enter;
    private javax.swing.JLabel iconuser;
    private javax.swing.JPanel inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel key;
    private javax.swing.JPanel left;
    private javax.swing.JLabel menu;
    private javax.swing.JLabel minimizar;
    private javax.swing.JPanel pregistro;
    private javax.swing.JLabel registrar1;
    private javax.swing.JPanel rigth;
    private javax.swing.JLabel textpassword;
    private javax.swing.JLabel textpassword1;
    private javax.swing.JLabel textuser;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usuario;
    private javax.swing.JLabel web1;
    // End of variables declaration//GEN-END:variables
}
