package view;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import models.Direccion;
import models.Estudio;
import models.Paciente;
import services.Repository;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        toggle = false;
        repo = new Repository();
        dtm = (DefaultTableModel)jTable2.getModel();
        dtm2 = (DefaultTableModel)jTable3.getModel();
        titulo.setText("BIENVENIDO ADMIN");
        rc.setVisible(false);
        rp.setVisible(false);
        bc.setVisible(false);
        bp.setVisible(false);
        initVisite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initVisite(){
        ArrayList<Object>pacientes = repo.leerDatos("pacientes");
        id = pacientes.size()+1;
        Vector<Object>pas = new Vector();
        for(Object a:pacientes){
            pas.add(((Paciente)a).getIdPaciente());
            pas.add(((Paciente)a).getName());
            pas.add(((Paciente)a).getLastName());
            pas.add(((Paciente)a).getBirthdate());
            pas.add(((Paciente)a).getAge());
            pas.add(((Paciente)a).getEmail());
            pas.add(((Paciente)a).getDirection().getCiudad());
            jComboBox4.addItem(((Paciente)a).getName()+" "+((Paciente)a).getLastName());
            dtm2.addRow(pas);
        }
        ArrayList<Object>consultas = repo.leerDatos("consultas");
        Vector<Object>con = new Vector();
        for(Object a:consultas){
            con.add(((Estudio)a).getPaciente().getName());
            con.add(((Estudio)a).getPaciente().getLastName());
            con.add(((Estudio)a).getDiagnostico());
            con.add(((Estudio)a).getTipoestudio());
            con.add(((Estudio)a).getPaquete());
            con.add(((Estudio)a).getMetodopago());
            con.add(((Estudio)a).getImporteTotal());
            
            dtm.addRow(con);
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jButton6 = new javax.swing.JButton();
        menusuperior = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        content = new javax.swing.JPanel();
        rc = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField6 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel40 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        rp = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField23 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jTextField24 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        bp = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jTextField26 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        bc = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField25 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu.setBackground(new java.awt.Color(255, 255, 255));
        menu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        menu.setForeground(new java.awt.Color(255, 102, 0));
        menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuMouseExited(evt);
            }
        });
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-job-seeker-64.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-job-seeker-64 (1).png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        menu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 80, 60));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sign-out-80.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-sign-out-80 (1).png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        menu.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 80, 70));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-male-64.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setContentAreaFilled(false);
        jButton4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-add-user-male-64 (1).png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        menu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 80, 60));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 108, 0));
        jLabel1.setText("Agregar paciente");
        menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 60));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 108, 0));
        jLabel2.setText("Crear consulta");
        menu.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 140, 60));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 108, 0));
        jLabel3.setText("Buscar consulta");
        menu.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 140, 60));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 108, 0));
        jLabel4.setText("Buscar paciente");
        menu.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 140, 60));

        jSeparator1.setForeground(new java.awt.Color(255, 108, 0));
        menu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 220, 10));

        jSeparator2.setForeground(new java.awt.Color(255, 108, 0));
        menu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 220, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 108, 0));
        menu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 220, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 108, 0));
        menu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 220, 10));

        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-create-64.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-create-64 (1).png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 80, 60));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menu-48.png"))); // NOI18N
        jButton5.setContentAreaFilled(false);
        jButton5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-menu-48 (1).png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        menu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));

        jSeparator5.setForeground(new java.awt.Color(255, 108, 0));
        menu.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 220, 10));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-personal-information-64.png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-personal-information-64 (1).png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        menu.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 80, 60));

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 570));

        menusuperior.setBackground(new java.awt.Color(255, 255, 255));
        menusuperior.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        menusuperior.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Copperplate Gothic Light", 0, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 102, 0));
        titulo.setText("Registro de consultas");
        menusuperior.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 430, 40));

        getContentPane().add(menusuperior, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 700, 60));

        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rc.setBackground(new java.awt.Color(255, 255, 255));
        rc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setBackground(new java.awt.Color(204, 204, 204));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rc.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, 200, 30));

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 102, 0));
        jLabel11.setText("Informacion pago");
        rc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 120, -1));

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 102, 0));
        jLabel12.setText("Tipo de estudio");
        rc.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 150, -1));

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Registrar");
        rc.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 460, 60, 20));

        jTextField9.setBackground(new java.awt.Color(204, 204, 204));
        jTextField9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rc.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 150, 30));

        jLabel15.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 102, 0));
        jLabel15.setText("Hora de consulta");
        rc.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 102, 0));
        jLabel16.setText("Metodo de pago");
        rc.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        jTextField11.setBackground(new java.awt.Color(204, 204, 204));
        jTextField11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rc.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 30));

        jLabel17.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 102, 0));
        jLabel17.setText("Doctor que refirio");
        rc.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jTextField12.setBackground(new java.awt.Color(204, 204, 204));
        jTextField12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rc.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 150, 30));

        jLabel18.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 102, 0));
        jLabel18.setText("Importe total");
        rc.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        jTextField13.setBackground(new java.awt.Color(204, 204, 204));
        jTextField13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rc.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 150, 30));

        jLabel19.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 102, 0));
        jLabel19.setText("Doctor que atendio");
        rc.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        rc.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, 20, 400));

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);
        rc.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 20, 400));

        jLabel20.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 102, 0));
        jLabel20.setText("Diagnostico");
        rc.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 102, 0));
        jLabel21.setText("Informacion del paciente");
        rc.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, -1));

        jComboBox1.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Tarjeta de credito", "Tarjeta de debito", "Efectivo", "Trasferencia bancaria" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        rc.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 150, 30));

        jComboBox2.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "none", "Simple", "Doble" }));
        jComboBox2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        rc.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 150, 30));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rc.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24.png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24 (1).png"))); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        rc.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, 30));

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-30.png"))); // NOI18N
        jButton8.setBorder(null);
        jButton8.setContentAreaFilled(false);
        jButton8.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-30 (1).png"))); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        rc.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, 40));

        jLabel22.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 102, 0));
        jLabel22.setText("Paquete");
        rc.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        jComboBox3.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        rc.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 240, 30));

        jLabel40.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 102, 0));
        jLabel40.setText("Pacientes");
        rc.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, -1, -1));

        jComboBox4.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        rc.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, 150, 30));

        content.add(rc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Visita por primera vez?");
        jLabel5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 40));

        jButton12.setText("si");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jButton13.setText("no");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        content.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 200, 110));

        rp.setBackground(new java.awt.Color(255, 255, 255));
        rp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 0));
        jLabel23.setText("Apellidos del paciente");
        rp.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 30));

        jTextField10.setBackground(new java.awt.Color(204, 204, 204));
        jTextField10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jTextField10.setEnabled(false);
        rp.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 30));

        jLabel24.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 102, 0));
        jLabel24.setText("Datos");
        rp.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, -1));

        jTextField14.setBackground(new java.awt.Color(204, 204, 204));
        jTextField14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, 150, 30));

        jLabel25.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 102, 0));
        jLabel25.setText("Ciudad");
        rp.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        jTextField15.setBackground(new java.awt.Color(204, 204, 204));
        jTextField15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, 30));

        jLabel26.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 102, 0));
        jLabel26.setText("Calle");
        rp.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        jTextField16.setBackground(new java.awt.Color(204, 204, 204));
        jTextField16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jTextField16.setEnabled(false);
        rp.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 150, 30));

        jLabel27.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 102, 0));
        jLabel27.setText("Fecha de registro");
        rp.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jTextField17.setBackground(new java.awt.Color(204, 204, 204));
        jTextField17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 150, 30));

        jLabel28.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 102, 0));
        jLabel28.setText("Telefono");
        rp.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, -1, -1));

        jTextField18.setBackground(new java.awt.Color(204, 204, 204));
        jTextField18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 150, 30));

        jLabel29.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 102, 0));
        jLabel29.setText("Colonia");
        rp.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, -1, -1));

        jTextField19.setBackground(new java.awt.Color(204, 204, 204));
        jTextField19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jTextField19.setEnabled(false);
        rp.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 50, 30));

        jLabel30.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 102, 0));
        jLabel30.setText("Id del paciente");
        rp.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        jTextField20.setBackground(new java.awt.Color(204, 204, 204));
        jTextField20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 30));

        jLabel31.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 102, 0));
        jLabel31.setText("Nombre del paciente");
        rp.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jTextField21.setBackground(new java.awt.Color(204, 204, 204));
        jTextField21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 30));

        jLabel32.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 102, 0));
        jLabel32.setText("Fecha de nacimiento");
        rp.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jTextField22.setBackground(new java.awt.Color(204, 204, 204));
        jTextField22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 150, 30));

        jLabel33.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 102, 0));
        jLabel33.setText("Correo Electronico");
        rp.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, -1, -1));

        jTextField23.setBackground(new java.awt.Color(204, 204, 204));
        jTextField23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 150, 30));

        jLabel34.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 102, 0));
        jLabel34.setText("Codigo Postal");
        rp.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, -1, -1));

        jSeparator8.setOrientation(javax.swing.SwingConstants.VERTICAL);
        rp.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 10, 440));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        rp.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 10, 440));

        jTextField24.setBackground(new java.awt.Color(204, 204, 204));
        jTextField24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        rp.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, 150, 30));

        jLabel35.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 102, 0));
        jLabel35.setText("Edad");
        rp.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, -1));

        jLabel36.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 102, 0));
        jLabel36.setText("Nombre de quien registra");
        rp.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel37.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 102, 0));
        jLabel37.setText("Direccion");
        rp.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        jLabel38.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 102, 0));
        jLabel38.setText("Informacion");
        rp.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-30.png"))); // NOI18N
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-login-30 (1).png"))); // NOI18N
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        rp.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 450, -1, 40));

        jLabel39.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 102, 0));
        jLabel39.setText("Finalizar");
        rp.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 460, -1, -1));

        content.add(rp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        bp.setBackground(new java.awt.Color(255, 255, 255));
        bp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Apellido", "Fecha nacimiento", "Edad", "Corrreo", "Ciudad"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        bp.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 450));

        jTextField26.setBackground(new java.awt.Color(204, 204, 204));
        jTextField26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        bp.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 102, 0));
        jLabel7.setText("Buscar");
        bp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24.png"))); // NOI18N
        jButton11.setBorder(null);
        jButton11.setContentAreaFilled(false);
        jButton11.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24 (1).png"))); // NOI18N
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        bp.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 30, 30));

        content.add(bp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        bc.setBackground(new java.awt.Color(255, 255, 255));
        bc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Diagnostico", "Estudio", "Paquete", "Metodo pago", "Total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        bc.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 450));

        jTextField25.setBackground(new java.awt.Color(204, 204, 204));
        jTextField25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        bc.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 180, 30));

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText("Buscar");
        bc.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-search-24 (1).png"))); // NOI18N
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        bc.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 30, 30));

        content.add(bc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        content.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 510));

        getContentPane().add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 700, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseEntered
        // TODO add your handling code here:
       
    }//GEN-LAST:event_menuMouseEntered

    private void menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered

    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited

    }//GEN-LAST:event_jButton1MouseExited

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
  
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited

    }//GEN-LAST:event_jButton3MouseExited

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton4MouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        toggle = !toggle;
        if(toggle){
            menu.setSize(220, 600);
        }else{
            menu.setSize(80, 600);
        }
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        dispose();
        new Login().setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            if(dtm.getRowCount()>0)for(int i=0;i<=dtm.getRowCount();i++)dtm.removeRow(i);
        
            ArrayList<Object>pas = new ArrayList();
            Estudio estudio = new Estudio();
            Paciente pasiente = new Paciente();
            
            String nombreApellido = String.valueOf(jComboBox4.getSelectedItem());
            String[] nas = nombreApellido.split(" ");
            pasiente.setName(nas[0]);
            pasiente.setFirstName(nas[1]);
            estudio.setPaciente(pasiente);
            estudio.setDiagnostico(jTextField6.getText());
            estudio.setTipoEstudio(String.valueOf(jComboBox3.getSelectedItem()));
            estudio.setPaquete(String.valueOf(jComboBox2.getSelectedItem()));
            estudio.setMetodopago(String.valueOf(jComboBox1.getSelectedItem()));
            estudio.setImporteTotal(Integer.parseInt(jTextField12.getText()));

            pas.add(estudio);
            repo.escribirDatos(pas, "consultas");
            jTextField14.setText("");
            jTextField19.setText("");
            jTextField20.setText("");
            jTextField8.setText("");
            jTextField21.setText("");
            jTextField24.setText("");
            jTextField21.setText("");
            initVisite();
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if(dtm2.getRowCount()>0)for(int i=0;i<=dtm2.getRowCount();i++)dtm2.removeRow(i);
        
        
        ArrayList<Object>pas = new ArrayList();
        
            Paciente paciente = new Paciente();
            Direccion direc = new Direccion();
            jTextField19.setText(String.valueOf(id));
            direc.setCiudad(jTextField14.getText());    
            
            paciente.setIdPaciente(Integer.parseInt(jTextField19.getText()));
            paciente.setName(jTextField20.getText());
            paciente.setFirstName(jTextField8.getText());
            paciente.setBirthdate(jTextField21.getText());
            paciente.setAge(Integer.parseInt(jTextField24.getText()));
            paciente.setEmail(jTextField21.getText());
            paciente.setDirection(direc);
            
            pas.add(paciente);
            repo.escribirDatos(pas, "pacientes");
            jTextField14.setText("");
            jTextField19.setText("");
            jTextField20.setText("");
            jTextField8.setText("");
            jTextField21.setText("");
            jTextField24.setText("");
            jTextField21.setText("");
            initVisite();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        rc.setVisible(true);
        bc.setVisible(false);
        rp.setVisible(false);
        bp.setVisible(false);
        titulo.setText("REGISTRO DE CONSULTAS");
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        titulo.setText("REGISTRO DE PACIENTES");
        rc.setVisible(false);
        bc.setVisible(false);
        bp.setVisible(false);
        rp.setVisible(true);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        jTextField10.setText("admin");
        LocalDate ld = LocalDate.now();
        jTextField16.setText(""+ld.getDayOfMonth()+"/ "+ld.getMonth()+"/ "+ld.getYear());
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        titulo.setText("BUSQUEDA DE CONSULTAS");
        rp.setVisible(false);
        rc.setVisible(false);
        bp.setVisible(false);
        bc.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        titulo.setText("BUSQUEDA DE PACIENTES");
        rp.setVisible(false);
        rc.setVisible(false);
        bc.setVisible(false);
        bp.setVisible(true);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
            jPanel1.setVisible(false);
            rc.setVisible(true);
            rp.setVisible(false);
            bc.setVisible(false);
            bp.setVisible(false);

    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
           titulo.setText("REGISTRO DE PACIENTES");
           jPanel1.setVisible(false);
           rc.setVisible(false);
           rp.setVisible(true);
           bc.setVisible(false);
           bp.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    /**
     * @param args the command line arguments
     */
    private int id;
    private DefaultTableModel dtm2;
    private DefaultTableModel dtm;
    private Repository repo;
    private boolean toggle;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bc;
    private javax.swing.JPanel bp;
    private javax.swing.JPanel content;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menusuperior;
    private javax.swing.JPanel rc;
    private javax.swing.JPanel rp;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
